# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "staging", "feature/deploy-action" ]
  pull_request:
    branches: [ "staging" ]

# See https://github.com/mnapoli/github-to-aws for how the AWS credentials work
permissions:
    id-token: write # This is required for requesting the JWT
    contents: read  # This is required for actions/checkout

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::413022200594:role/github-deploy-brawnang-site-frontend
        role-session-name: github-deploy
        aws-region: us-east-1

    - name: Open SG
      run: bash devops/open-sg.sh

    - name: Build Node.js site
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - run: yarn
    - run: npm run build --if-present


    - name: Deploy
      env:
        PRIVATE_KEY: ${{ secrets.SSH_STAGE_PRIVATE_KEY }}
        HOSTNAME: ${{ secrets.SSH_STAGE_HOST }}
        USER_NAME: ${{ secrets.SSH_STAGE_USER_NAME }}
      run: |
        MYIP=$(curl http://ipecho.net/plain)
        echo $MYIP
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        exit
        scp -v -o StrictHostKeyChecking=no -i private_key -r dist ${USER_NAME}@${HOSTNAME}:dist-new
        ssh -v -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
        pwd
        mv dist/ dist-old/
        mv dist-new/ dist/
        echo apache '

    - name: Close Security Group
      if: always()
      run: bash devops/close-sg.sh
